version: "2"

services:
  db:
    build: db/
    env_file: .env
    ports:
      - "32099:5432"
    volumes:
      - ./shared:/var/app/db-bootstrap/shared
    volumes_from:
      - data

  data:
    image: postgres
    restart: "no"
    command: "true"
    volumes:
      - /var/lib/postgresql
